import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { applyTsPathAlias, defaultTsPathAlias, resolveTsPathAlias } from "./ts-path-alias.js";

describe("defaultTsPathAlias", () => {
  it("derives a kebab-cased alias scoped under /apigen", () => {
    expect(defaultTsPathAlias("PetStore")).toBe("@pet-store/apigen");
  });
});

describe("resolveTsPathAlias", () => {
  it("autogenerates an alias when given boolean true", () => {
    expect(resolveTsPathAlias(true, "PetStore")).toBe("@pet-store/apigen");
  });

  it('autogenerates an alias when given the literal string "true"', () => {
    expect(resolveTsPathAlias("true", "PetStore")).toBe("@pet-store/apigen");
  });

  it("uses an explicit alias string as-is", () => {
    expect(resolveTsPathAlias("@api/pet-store", "PetStore")).toBe("@api/pet-store");
  });
});

describe("applyTsPathAlias", () => {
  let dir: string;
  let tsconfigPath: string;
  let outFile: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "apigen-ts-path-alias-"));
    tsconfigPath = join(dir, "tsconfig.json");
    outFile = join(dir, "lib", "generated", "pet-store.client.ts");
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it("throws a clear error when the tsconfig doesn't exist", async () => {
    await expect(
      applyTsPathAlias({ name: "PetStore", outFile, tspathalias: true, tsconfigPath }),
    ).rejects.toThrow(/no tsconfig was found/);
  });

  it("adds an autogenerated alias entry, preserving existing tsconfig content", async () => {
    await writeFile(
      tsconfigPath,
      JSON.stringify({ compilerOptions: { target: "ES2022", strict: true } }, null, 2),
      "utf8",
    );

    await applyTsPathAlias({ name: "PetStore", outFile, tspathalias: true, tsconfigPath });

    const written = JSON.parse(await readFile(tsconfigPath, "utf8"));
    expect(written.compilerOptions.target).toBe("ES2022");
    expect(written.compilerOptions.strict).toBe(true);
    expect(written.compilerOptions.paths).toEqual({
      "@pet-store/apigen": ["./lib/generated/pet-store.client.ts"],
    });
  });

  it("uses an explicit alias string when given one", async () => {
    await writeFile(tsconfigPath, JSON.stringify({ compilerOptions: {} }, null, 2), "utf8");

    await applyTsPathAlias({
      name: "PetStore",
      outFile,
      tspathalias: "@api/pet-store",
      tsconfigPath,
    });

    const written = JSON.parse(await readFile(tsconfigPath, "utf8"));
    expect(written.compilerOptions.paths).toEqual({
      "@api/pet-store": ["./lib/generated/pet-store.client.ts"],
    });
  });

  it("preserves comments already present in the tsconfig", async () => {
    await writeFile(
      tsconfigPath,
      '{\n  // keep me\n  "compilerOptions": {\n    "target": "ES2022"\n  }\n}\n',
      "utf8",
    );

    await applyTsPathAlias({ name: "PetStore", outFile, tspathalias: true, tsconfigPath });

    const written = await readFile(tsconfigPath, "utf8");
    expect(written).toContain("// keep me");
  });

  it("does not touch an existing unrelated paths entry", async () => {
    await writeFile(
      tsconfigPath,
      JSON.stringify({ compilerOptions: { paths: { "@other/thing": ["./other.ts"] } } }, null, 2),
      "utf8",
    );

    await applyTsPathAlias({ name: "PetStore", outFile, tspathalias: true, tsconfigPath });

    const written = JSON.parse(await readFile(tsconfigPath, "utf8"));
    expect(written.compilerOptions.paths["@other/thing"]).toEqual(["./other.ts"]);
    expect(written.compilerOptions.paths["@pet-store/apigen"]).toEqual([
      "./lib/generated/pet-store.client.ts",
    ]);
  });

  it("replaces the previous alias for the same api name on a re-run with a different alias", async () => {
    await writeFile(tsconfigPath, JSON.stringify({ compilerOptions: {} }, null, 2), "utf8");

    await applyTsPathAlias({ name: "PetStore", outFile, tspathalias: true, tsconfigPath });
    await applyTsPathAlias({
      name: "PetStore",
      outFile,
      tspathalias: "@api/pet-store",
      tsconfigPath,
    });

    const written = JSON.parse(await readFile(tsconfigPath, "utf8"));
    expect(written.compilerOptions.paths).toEqual({
      "@api/pet-store": ["./lib/generated/pet-store.client.ts"],
    });
  });

  it("keeps a stable alias across re-runs with the same api name and alias", async () => {
    await writeFile(tsconfigPath, JSON.stringify({ compilerOptions: {} }, null, 2), "utf8");

    await applyTsPathAlias({ name: "PetStore", outFile, tspathalias: true, tsconfigPath });
    await applyTsPathAlias({ name: "PetStore", outFile, tspathalias: true, tsconfigPath });

    const written = JSON.parse(await readFile(tsconfigPath, "utf8"));
    expect(written.compilerOptions.paths).toEqual({
      "@pet-store/apigen": ["./lib/generated/pet-store.client.ts"],
    });
  });

  it("keeps a different api name's alias untouched when another api name's alias changes", async () => {
    await writeFile(tsconfigPath, JSON.stringify({ compilerOptions: {} }, null, 2), "utf8");
    const otherOutFile = join(dir, "lib", "generated", "user.client.ts");

    await applyTsPathAlias({ name: "PetStore", outFile, tspathalias: true, tsconfigPath });
    await applyTsPathAlias({
      name: "User",
      outFile: otherOutFile,
      tspathalias: true,
      tsconfigPath,
    });
    await applyTsPathAlias({
      name: "PetStore",
      outFile,
      tspathalias: "@api/pet-store",
      tsconfigPath,
    });

    const written = JSON.parse(await readFile(tsconfigPath, "utf8"));
    expect(written.compilerOptions.paths).toEqual({
      "@user/apigen": ["./lib/generated/user.client.ts"],
      "@api/pet-store": ["./lib/generated/pet-store.client.ts"],
    });
  });
});
